name: "chatgpthing:release"

on:
  push:
    tags:
      - chatgpthing-v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Build the Chrome extension
        run: pnpm build --filter=./apps/chatgpthing
      - name: Package the extension into a zip artifact for chrome
        run: pnpm package --filter=./apps/chatgpthing
      - name: Package the extension into a zip artifact for firefox
        run: pnpm build:firefox -- --zip --filter=./apps/chatgpthing
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.CHATGPTHING_KEYS }}
          chrome-file: apps/chatgpthing/build/chrome-mv3-prod.zip
          firefox-file: apps/chatgpthing/build/firefox-prod.zip
