on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}
